'use client';
import {useEffect,useRef,useState} from 'react';
import {cafeCall,rupees} from '@/lib/cafe-api';
import {Button} from '@/components/ui/button';
type Snapshot={runtime_id:string;revision:number;ended_at:string|null;billing:{is_final:boolean;total_paise:number;wallet_funded_paise:number;collected_paise:number;amount_due_paise:number}};
export default function ExtensionSettlement({runtimeId,vendorId,onClose,onUpdated}:{runtimeId:string;vendorId:number;onClose:()=>void;onUpdated:()=>void}){
 const [data,setData]=useState<Snapshot|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const locked=useRef(false);
 const prefix=`/${vendorId}/extensions/${runtimeId}`;
 useEffect(()=>{let alive=true;setData(null);cafeCall<Snapshot>(prefix).then(v=>{if(alive)setData(v)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[prefix]);
 async function mutate(kind:string,body:Record<string,unknown>){if(!data||locked.current)return;locked.current=true;setBusy(true);setError('');try{const result=await cafeCall<Snapshot>(`${prefix}/${kind}`,{...body,revision:data.revision,idempotency_key:`settlement-${runtimeId}-${data.revision}-${kind}-${body.method||''}`});setData(result);onUpdated();}catch(e){setError(e instanceof Error?e.message:'Could not complete');setData(null);try{setData(await cafeCall<Snapshot>(prefix));}catch{}}finally{locked.current=false;setBusy(false)}}
 return <div className="fixed inset-0 z-[1500] flex items-center justify-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label="Extension settlement"><section className="w-full max-w-md rounded-xl border bg-background p-5"><h2 className="text-lg font-semibold">Session extension settlement</h2><p className="mt-1 text-xs text-muted-foreground">Original booking and food payments remain in booking billing.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-400">{error}</p>}{!data?<p className="py-6 text-sm">Loading current charges…</p>:<><dl className="my-4 space-y-2 text-sm"><div className="flex justify-between"><dt>Extra time played</dt><dd>{rupees(data.billing.total_paise)}</dd></div><div className="flex justify-between"><dt>Paid from cafe wallet</dt><dd>{rupees(data.billing.wallet_funded_paise)}</dd></div><div className="flex justify-between"><dt>Already collected</dt><dd>{rupees(data.billing.collected_paise)}</dd></div><div className="flex justify-between border-t pt-2 font-semibold"><dt>{data.ended_at?'Final amount due':'Accrued amount due'}</dt><dd>{rupees(data.billing.amount_due_paise)}</dd></div></dl>{!data.ended_at?<Button className="w-full" disabled={busy} onClick={()=>mutate('end',{mode:'now'})}>End session and finalize charges</Button>:data.billing.amount_due_paise>0?<div className="grid grid-cols-2 gap-2">{['cash','cafe_upi'].map(method=><Button key={method} disabled={busy} onClick={()=>{if(window.confirm(`Confirm ${rupees(data.billing.amount_due_paise)} was received via ${method==='cash'?'cash':'UPI'}?`))void mutate('settle',{method,amount_paise:data.billing.amount_due_paise})}}>Received {method==='cash'?'cash':'UPI'}</Button>)}</div>:<p className="text-sm text-emerald-500">Extension charges settled.</p>}</>}<Button className="mt-3 w-full" variant="outline" disabled={busy} onClick={onClose}>Close</Button></section></div>
}
