'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useAccess} from '@/app/context/AccessContext';
import {useSocket} from '@/app/context/SocketContext';
import {cafeCall,rupees} from '@/lib/cafe-api';
import {Button} from '@/components/ui/button';
type Session={runtime_id:string;revision:number;state:string;ended_at:string|null;request_id:string|null;gamer_name:string;console_name:string;extension:{reason_code:string|null;requested_price_paise:number|null};billing:{amount_due_paise:number}};
type Notice={id:string;runtime_id:string;kind:string};
export default function SessionExtensionWorkspace(){
 const {selectedCafeId,activeStaff,can}=useAccess();const {socket}=useSocket();const [items,setItems]=useState<Session[]>([]);const [notices,setNotices]=useState<Notice[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const lock=useRef(false);const context=useRef('');context.current=`${selectedCafeId}:${activeStaff?.id}`;
 const refresh=useCallback(async()=>{if(!selectedCafeId)return;const key=`${selectedCafeId}:${activeStaff?.id}`;const data=await cafeCall<{items:Session[];notices:Notice[]}>(`/${selectedCafeId}/extensions`);if(context.current!==key)return;setItems(data.items);setNotices(data.notices);setError('');setLoading(false);},[selectedCafeId,activeStaff?.id]);
 useEffect(()=>{let alive=true;setLoading(true);setItems([]);setNotices([]);const update=()=>{if(alive)void refresh().catch(e=>{if(alive){setError(e.message);setLoading(false);}})};update();const poll=setInterval(update,15000);socket?.on('session.updated',update);socket?.on('connect',update);return()=>{alive=false;clearInterval(poll);socket?.off('session.updated',update);socket?.off('connect',update)}},[refresh,socket]);
 async function action(row:Session,kind:string,data:Record<string,unknown>){if(lock.current)return;lock.current=true;setBusy(true);try{await cafeCall(`/${selectedCafeId}/extensions/${row.runtime_id}/${kind}`,{...data,revision:row.revision,idempotency_key:`extension-${kind}-${row.runtime_id}-${row.revision}-${String(data.method||data.decision||'')}`});await refresh();}catch(e){setError(e instanceof Error?e.message:'Request failed');}finally{lock.current=false;setBusy(false);}}
 if(!activeStaff)return null;
 const relevant=items.filter(s=>s.request_id||s.billing.amount_due_paise>0);
 return <section className="mb-4 rounded-lg border p-3" aria-label="Session extension requests"><h4 className="text-sm font-semibold">Session extensions and credit</h4>{loading?<p className="mt-2 text-xs">Loading authoritative session data…</p>:error?<p role="alert" className="mt-2 text-xs text-red-400">{error}</p>:<>{notices.slice(0,10).map(n=><div key={n.id} className="mt-2 flex items-center justify-between gap-2 text-xs"><span>{n.kind.replaceAll('_',' ')}</span><button disabled={busy} className="underline" onClick={async()=>{try{await cafeCall(`/${selectedCafeId}/extension-notices/${n.id}/read`,{});await refresh();}catch(e){setError(e instanceof Error?e.message:'Request failed');}}}>Mark read</button></div>)}{relevant.map(s=><div key={s.runtime_id} className="mt-3 border-t pt-3"><p className="text-sm font-medium">{s.gamer_name} · {s.console_name}</p><p className="mt-1 text-xs text-muted-foreground">{s.state.replaceAll('_',' ')} · Due {rupees(s.billing.amount_due_paise)}{s.request_id&&s.extension.requested_price_paise!=null&&` · Requested extension ${rupees(s.extension.requested_price_paise)}`}</p><div className="mt-2 flex flex-wrap gap-2">{s.request_id&&can('booking.manage')&&<>{activeStaff.role==='owner'&&<Button size="sm" disabled={busy} onClick={()=>action(s,'decision',{request_id:s.request_id,decision:'approve'})}>Approve</Button>}{s.state==='conflict_pending'&&<Button size="sm" disabled={busy} onClick={()=>action(s,'decision',{request_id:s.request_id,decision:'retry'})}>Retry after resolving booking</Button>}{activeStaff.role==='owner'&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(s,'decision',{request_id:s.request_id,decision:'reject'})}>Reject</Button>}</>}{!s.ended_at&&can('booking.manage')&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>action(s,'end',{mode:'now'})}>End session</Button>}{s.ended_at&&s.billing.amount_due_paise>0&&can('wallet.topup')&&['cash','cafe_upi'].map(method=><Button key={method} size="sm" disabled={busy} onClick={()=>{if(window.confirm(`Confirm ${rupees(s.billing.amount_due_paise)} was actually received via ${method==='cash'?'cash':'UPI'}?`))void action(s,'settle',{method,amount_paise:s.billing.amount_due_paise});}}>Received {method==='cash'?'cash':'UPI'}</Button>)}</div>{s.state==='conflict_pending'&&<p className="mt-2 text-xs text-amber-400">Resolve the other booking in Schedule first. This action cannot displace it.</p>}</div>)}{!notices.length&&!relevant.length&&<p className="mt-2 text-xs text-muted-foreground">No pending extension requests or credit settlements.</p>}</>}</section>
}
